name=input("Enter your name: ")
major = input("Enter your major: ")
classification = input("Enter your classification: ")
year = input("Enter current year: ")
print()
print("STUDENT RECORDS".center(72))
print()
print ( " {0:^18s} {1:^25s} {2:^16s} {3:>7s} ". format ("Name","Major","Classification","Year"))
print ( " {0:<20s} {0:^22s} {2:<19s} {1:^7s} ". format ("="*20 , "="*6,"="*18))
print ( " {0:<21s} {1:<21s} {2:<19s} {3:<7s} ". format (name,major,classification,year))
print ("\n")
print()
I = input ( "Press enter to exit ")
